In [1]:
import numpy as np


In [2]:
# Define the multiway array
array = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]], [[90, 100], [110, 120]]])

# Define the dimensions
time = ["Jan", "Feb", "Mar"]
product_categories = ["Clothing", "Electronics"]
geographical_regions = ["Region1", "Region2"]

# Print the original array
print("Original Array:")
print(array)

# Compute the sum along the time dimension
time_sum = np.sum(array, axis=0)
print("\nSum along time dimension:")
print(time_sum)

# Compute the mean along the product categories dimension
product_categories_mean = np.mean(array, axis=1)
print("\nMean along product categories dimension:")
print(product_categories_mean)

# Compute the sum along the geographical regions dimension
geographical_regions_sum = np.sum(array, axis=2)
print("\nSum along geographical regions dimension:")
print(geographical_regions_sum)

Original Array:
[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]

Sum along time dimension:
[[150 180]
 [210 240]]

Mean along product categories dimension:
[[ 20.  30.]
 [ 60.  70.]
 [100. 110.]]

Sum along geographical regions dimension:
[[ 30  70]
 [110 150]
 [190 230]]
